name: build_pavadan

on:
  watch:
    types: [started]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
   
env:
  repo_url: https://github.com/andy-padavan/rt-n56u
  repo_branch: master
  repo_os: pavanda
  model: RT-AC1200HP


jobs:
    build:
      runs-on: ubuntu-20.04

      steps:
        - name: 获取本仓库源码
          uses: actions/checkout@main
  
        - name: 清理＆配置环境
          run: |
            docker rmi `docker images -q`
            sudo apt update
            sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            	fakeroot kmod cpio git python3-docutils gettext automake autopoint \
            	texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            	libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
          
        - name: 获取源码
          run: |
              cd /
              git clone --recurse-submodules $repo_url -b $repo_branch /opt/rt-n56u
              cd /opt/rt-n56u/toolchain-mipsel
              cd /opt/rt-n56u/toolchain-mipsel && ./clean_sources && ./build_toolchain_3.4.x
#              git clone https://github.com/zhlhlf/jczhl-package /opt/rt-n56u/jczhl-package
#              cd /opt/rt-n56u
#              mv jczhl-package/$model/$model.config /opt/rt-n56u/trunk/configs/templates/$model.config
#              mv jczhl-package/$model /opt/rt-n56u/trunk/configs/boards
#              cd /opt/rt-n56u/toolchain-mipsel
#              sh dl_toolchain.sh

        - name: SSH connection to Actions
          uses: P3TERX/ssh2actions@v1.0.0
           env:
              TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
              TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

        - name: 编译固件
          run: |
              cd /opt/rt-n56u/trunk
              fakeroot ./build_firmware_modify $model
             
        - name: 移动生成至zhlhlf目录
          run: |
           mkdir zhlhlf
           rm -rf zhlhlf/*           
           mv /opt/rt-n56u/trunk/images/*.trx zhlhlf         
                              
        - name: Upload artifact
          uses: actions/upload-artifact@master
          with:
           name: pavadan
           path: zhlhlf/
